if(EXISTS "C:/Users/UserName/Dev/HellEngine/build_fresh/boss_phase_tests-b12d07c_tests.cmake")
  include("C:/Users/UserName/Dev/HellEngine/build_fresh/boss_phase_tests-b12d07c_tests.cmake")
else()
  add_test(boss_phase_tests_NOT_BUILT-b12d07c boss_phase_tests_NOT_BUILT-b12d07c)
endif()
