if(EXISTS "C:/Users/UserName/Dev/HellEngine/build_fresh/collision_correctness_tests-b12d07c_tests.cmake")
  include("C:/Users/UserName/Dev/HellEngine/build_fresh/collision_correctness_tests-b12d07c_tests.cmake")
else()
  add_test(collision_correctness_tests_NOT_BUILT-b12d07c collision_correctness_tests_NOT_BUILT-b12d07c)
endif()
