if(EXISTS "C:/Users/UserName/Dev/HellEngine/build_fresh/content_fuzz_tests-b12d07c_tests.cmake")
  include("C:/Users/UserName/Dev/HellEngine/build_fresh/content_fuzz_tests-b12d07c_tests.cmake")
else()
  add_test(content_fuzz_tests_NOT_BUILT-b12d07c content_fuzz_tests_NOT_BUILT-b12d07c)
endif()
