# CMake generated Testfile for 
# Source directory: C:/Users/UserName/Dev/HellEngine
# Build directory: C:/Users/UserName/Dev/HellEngine/build_fresh
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("C:/Users/UserName/Dev/HellEngine/build_fresh/render2d_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/projectile_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/pattern_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/content_packer_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/entity_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/boss_phase_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/editor_tools_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/replay_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/projectile_behavior_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/pattern_graph_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/collision_correctness_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/determinism_property_tests-b12d07c_include.cmake")
include("C:/Users/UserName/Dev/HellEngine/build_fresh/content_fuzz_tests-b12d07c_include.cmake")
add_test([=[timing_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/timing_tests.exe")
set_tests_properties([=[timing_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;366;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[config_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/config_tests.exe")
set_tests_properties([=[config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;367;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[content_packer_generate]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "chdir" "C:/Users/UserName/Dev/HellEngine" "C:/Users/UserName/Dev/HellEngine/build_fresh/ContentPacker.exe" "--input" "data" "--output" "C:/Users/UserName/Dev/HellEngine/build_fresh/content_test.pak")
set_tests_properties([=[content_packer_generate]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;373;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[content_import_pipeline_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/content_import_pipeline_tests.exe")
set_tests_properties([=[content_import_pipeline_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;379;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[trait_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/trait_tests.exe")
set_tests_properties([=[trait_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;381;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[archetype_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/archetype_tests.exe")
set_tests_properties([=[archetype_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;382;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[run_structure_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/run_structure_tests.exe")
set_tests_properties([=[run_structure_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;384;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[meta_progression_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/meta_progression_tests.exe")
set_tests_properties([=[meta_progression_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;385;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[persistence_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/persistence_tests.exe")
set_tests_properties([=[persistence_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;386;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[upgrade_ui_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/upgrade_ui_tests.exe")
set_tests_properties([=[upgrade_ui_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;389;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[upgrade_ui_model_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/upgrade_ui_model_tests.exe")
set_tests_properties([=[upgrade_ui_model_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;390;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[pattern_generator_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/pattern_generator_tests.exe")
set_tests_properties([=[pattern_generator_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;393;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[pattern_graph_perf_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/pattern_graph_perf_tests.exe")
set_tests_properties([=[pattern_graph_perf_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;394;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[encounter_graph_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/encounter_graph_tests.exe")
set_tests_properties([=[encounter_graph_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;395;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[difficulty_scaling_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/difficulty_scaling_tests.exe")
set_tests_properties([=[difficulty_scaling_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;396;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[diagnostics_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/diagnostics_tests.exe")
set_tests_properties([=[diagnostics_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;397;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[gpu_bullets_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/gpu_bullets_tests.exe")
set_tests_properties([=[gpu_bullets_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;398;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[golden_replay_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/golden_replay_tests.exe")
set_tests_properties([=[golden_replay_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;399;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[benchmark_suite_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/benchmark_suite_tests.exe")
set_tests_properties([=[benchmark_suite_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;400;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[public_api_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/public_api_tests.exe")
set_tests_properties([=[public_api_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;401;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[renderer_smoke_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/renderer_smoke_tests.exe")
set_tests_properties([=[renderer_smoke_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;402;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[palette_fx_templates_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/palette_fx_templates_tests.exe")
set_tests_properties([=[palette_fx_templates_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;403;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[modern_renderer_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/modern_renderer_tests.exe")
set_tests_properties([=[modern_renderer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;404;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[defensive_special_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/defensive_special_tests.exe")
set_tests_properties([=[defensive_special_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;405;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[gameplay_session_state_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/gameplay_session_state_tests.exe")
set_tests_properties([=[gameplay_session_state_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;406;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[standards_tests]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/standards_tests.exe")
set_tests_properties([=[standards_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;407;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
add_test([=[determinism_cross_config_test]=] "C:/Users/UserName/Dev/HellEngine/build_fresh/determinism_cross_config_test.exe")
set_tests_properties([=[determinism_cross_config_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;354;add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;363;engine_register_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;411;engine_add_test;C:/Users/UserName/Dev/HellEngine/CMakeLists.txt;0;")
subdirs("_deps/sdl2-build")
subdirs("_deps/sdl2_mixer-build")
subdirs("_deps/nlohmann_json-build")
subdirs("_deps/catch2-build")
