if(EXISTS "C:/Users/UserName/Dev/HellEngine/build_fresh/determinism_property_tests-b12d07c_tests.cmake")
  include("C:/Users/UserName/Dev/HellEngine/build_fresh/determinism_property_tests-b12d07c_tests.cmake")
else()
  add_test(determinism_property_tests_NOT_BUILT-b12d07c determinism_property_tests_NOT_BUILT-b12d07c)
endif()
