if(EXISTS "C:/Users/UserName/Dev/HellEngine/build_fresh/editor_tools_tests-b12d07c_tests.cmake")
  include("C:/Users/UserName/Dev/HellEngine/build_fresh/editor_tools_tests-b12d07c_tests.cmake")
else()
  add_test(editor_tools_tests_NOT_BUILT-b12d07c editor_tools_tests_NOT_BUILT-b12d07c)
endif()
