if(EXISTS "C:/Users/UserName/Dev/HellEngine/build_fresh/pattern_graph_tests-b12d07c_tests.cmake")
  include("C:/Users/UserName/Dev/HellEngine/build_fresh/pattern_graph_tests-b12d07c_tests.cmake")
else()
  add_test(pattern_graph_tests_NOT_BUILT-b12d07c pattern_graph_tests_NOT_BUILT-b12d07c)
endif()
