if(EXISTS "C:/Users/UserName/Dev/HellEngine/build_fresh/projectile_tests-b12d07c_tests.cmake")
  include("C:/Users/UserName/Dev/HellEngine/build_fresh/projectile_tests-b12d07c_tests.cmake")
else()
  add_test(projectile_tests_NOT_BUILT-b12d07c projectile_tests_NOT_BUILT-b12d07c)
endif()
