if(EXISTS "C:/Users/UserName/Dev/HellEngine/build_fresh/render2d_tests-b12d07c_tests.cmake")
  include("C:/Users/UserName/Dev/HellEngine/build_fresh/render2d_tests-b12d07c_tests.cmake")
else()
  add_test(render2d_tests_NOT_BUILT-b12d07c render2d_tests_NOT_BUILT-b12d07c)
endif()
